/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip,
} = require("./runtime/index-browser.js");

const Prisma = {};

exports.Prisma = Prisma;
exports.$Enums = {};

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773",
};

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.Decimal = Decimal;

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.validator = Public.validator;

/**
 * Extensions
 */
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull;
Prisma.JsonNull = objectEnumValues.instances.JsonNull;
Prisma.AnyNull = objectEnumValues.instances.AnyNull;

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull,
};

/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable",
});

exports.Prisma.UserScalarFieldEnum = {
  id: "id",
  email: "email",
  firstName: "firstName",
  lastName: "lastName",
  phone: "phone",
  role: "role",
  isActive: "isActive",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
};

exports.Prisma.ProfileScalarFieldEnum = {
  id: "id",
  avatar: "avatar",
  bio: "bio",
  address: "address",
  city: "city",
  state: "state",
  zipCode: "zipCode",
  country: "country",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  userId: "userId",
};

exports.Prisma.BusinessScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description",
  address: "address",
  city: "city",
  state: "state",
  zipCode: "zipCode",
  country: "country",
  phone: "phone",
  website: "website",
  logo: "logo",
  isVerified: "isVerified",
  isActive: "isActive",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  ownerId: "ownerId",
};

exports.Prisma.VehicleScalarFieldEnum = {
  id: "id",
  make: "make",
  model: "model",
  year: "year",
  color: "color",
  licensePlate: "licensePlate",
  vin: "vin",
  mileage: "mileage",
  seats: "seats",
  transmission: "transmission",
  fuelType: "fuelType",
  pricePerDay: "pricePerDay",
  pricePerWeek: "pricePerWeek",
  pricePerMonth: "pricePerMonth",
  description: "description",
  features: "features",
  isAvailable: "isAvailable",
  isActive: "isActive",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  businessId: "businessId",
  ownerId: "ownerId",
};

exports.Prisma.VehiclePhotoScalarFieldEnum = {
  id: "id",
  url: "url",
  caption: "caption",
  isPrimary: "isPrimary",
  createdAt: "createdAt",
  vehicleId: "vehicleId",
};

exports.Prisma.BookingScalarFieldEnum = {
  id: "id",
  startDate: "startDate",
  endDate: "endDate",
  totalDays: "totalDays",
  totalPrice: "totalPrice",
  status: "status",
  pickupLocation: "pickupLocation",
  dropoffLocation: "dropoffLocation",
  specialRequests: "specialRequests",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  userId: "userId",
  vehicleId: "vehicleId",
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: "id",
  amount: "amount",
  currency: "currency",
  status: "status",
  method: "method",
  transactionId: "transactionId",
  receiptUrl: "receiptUrl",
  processedAt: "processedAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  bookingId: "bookingId",
  userId: "userId",
};

exports.Prisma.MessageScalarFieldEnum = {
  id: "id",
  type: "type",
  content: "content",
  isRead: "isRead",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  senderId: "senderId",
  receiverId: "receiverId",
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: "id",
  rating: "rating",
  comment: "comment",
  isVerified: "isVerified",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  authorId: "authorId",
  receiverId: "receiverId",
  vehicleId: "vehicleId",
};

exports.Prisma.DocumentScalarFieldEnum = {
  id: "id",
  type: "type",
  name: "name",
  url: "url",
  description: "description",
  expiresAt: "expiresAt",
  isVerified: "isVerified",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  userId: "userId",
  businessId: "businessId",
};

exports.Prisma.TravelLogScalarFieldEnum = {
  id: "id",
  startMileage: "startMileage",
  endMileage: "endMileage",
  startLocation: "startLocation",
  endLocation: "endLocation",
  notes: "notes",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  bookingId: "bookingId",
};

exports.Prisma.TravelPhotoScalarFieldEnum = {
  id: "id",
  url: "url",
  caption: "caption",
  createdAt: "createdAt",
  travelLogId: "travelLogId",
};

exports.Prisma.SortOrder = {
  asc: "asc",
  desc: "desc",
};

exports.Prisma.QueryMode = {
  default: "default",
  insensitive: "insensitive",
};

exports.Prisma.NullsOrder = {
  first: "first",
  last: "last",
};
exports.UserRole = exports.$Enums.UserRole = {
  OWNER: "OWNER",
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
};

exports.BookingStatus = exports.$Enums.BookingStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

exports.MessageType = exports.$Enums.MessageType = {
  BOOKING_INQUIRY: "BOOKING_INQUIRY",
  GENERAL: "GENERAL",
  SUPPORT: "SUPPORT",
  SYSTEM: "SYSTEM",
};

exports.Prisma.ModelName = {
  User: "User",
  Profile: "Profile",
  Business: "Business",
  Vehicle: "Vehicle",
  VehiclePhoto: "VehiclePhoto",
  Booking: "Booking",
  Payment: "Payment",
  Message: "Message",
  Review: "Review",
  Document: "Document",
  TravelLog: "TravelLog",
  TravelPhoto: "TravelPhoto",
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message;
        const runtime = getRuntime();
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message =
            "PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `" +
            runtime.prettyName +
            "`).";
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`;

        throw new Error(message);
      },
    });
  }
}

exports.PrismaClient = PrismaClient;

Object.assign(exports, Prisma);
